In [1]:
import pandas as pd

In [3]:
oscar_csv = "Resources/the_oscar_award.csv"
oscar_df= pd.read_csv(oscar_csv)

In [4]:
oscar_df.columns

Index(['year_film', 'year_ceremony', 'ceremony', 'category', 'name', 'film',
       'winner'],
      dtype='object')

In [21]:
oscar_renamed = oscar_df.rename(columns={'year_film': 'O_Year',
                                         'category': 'O_Category',
                                         'name': 'O_Nominee',
                                         'film': 'O_Film Title',
                                         'winner': 'O_Win'})
oscar_renamed

,O_Year,year_ceremony,ceremony,O_Category,O_Nominee,O_Film Title,O_Win
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...,...,...
10390,2019,2020,92,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True
10391,2019,2020,92,JEAN HERSHOLT HUMANITARIAN AWARD,Geena Davis,NaN,True
10392,2019,2020,92,HONORARY AWARD,David Lynch,NaN,True
10393,2019,2020,92,HONORARY AWARD,Wes Studi,NaN,True
10394,2019,2020,92,HONORARY AWARD,Lina Wertmüller,NaN,True

In [22]:
oscar_reduced = oscar_renamed[['O_Year', 'O_Category', 'O_Nominee', 'O_Film Title', 'O_Win']]
oscar_reduced

,O_Year,O_Category,O_Nominee,O_Film Title,O_Win
0,1927,ACTOR,Richard Barthelmess,The Noose,False
1,1927,ACTOR,Emil Jannings,The Last Command,True
2,1927,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...
10390,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True
10391,2019,JEAN HERSHOLT HUMANITARIAN AWARD,Geena Davis,NaN,True
10392,2019,HONORARY AWARD,David Lynch,NaN,True
10393,2019,HONORARY AWARD,Wes Studi,NaN,True
10394,2019,HONORARY AWARD,Lina Wertmüller,NaN,True

In [23]:
oscar_reduced.dtypes

O_Year           int64
O_Category      object
O_Nominee       object
O_Film Title    object
O_Win             bool
dtype: object

In [25]:
oscar_year = oscar_reduced.loc[(oscar_reduced['O_Year'] >= 1970)]
oscar_year

,O_Year,O_Category,O_Nominee,O_Film Title,O_Win
4773,1970,ACTOR,Melvyn Douglas,I Never Sang for My Father,False
4774,1970,ACTOR,James Earl Jones,The Great White Hope,False
4775,1970,ACTOR,Jack Nicholson,Five Easy Pieces,False
4776,1970,ACTOR,Ryan O'Neal,Love Story,False
4777,1970,ACTOR,George C. Scott,Patton,True
...,...,...,...,...,...
10390,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True
10391,2019,JEAN HERSHOLT HUMANITARIAN AWARD,Geena Davis,NaN,True
10392,2019,HONORARY AWARD,David Lynch,NaN,True
10393,2019,HONORARY AWARD,Wes Studi,NaN,True
10394,2019,HONORARY AWARD,Lina Wertmüller,NaN,True

In [26]:
oscar_year = oscar_year.dropna(how='any')
oscar_year

,O_Year,O_Category,O_Nominee,O_Film Title,O_Win
4773,1970,ACTOR,Melvyn Douglas,I Never Sang for My Father,False
4774,1970,ACTOR,James Earl Jones,The Great White Hope,False
4775,1970,ACTOR,Jack Nicholson,Five Easy Pieces,False
4776,1970,ACTOR,Ryan O'Neal,Love Story,False
4777,1970,ACTOR,George C. Scott,Patton,True
...,...,...,...,...,...
10386,2019,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
10387,2019,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
10388,2019,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
10389,2019,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
10390,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True

In [27]:
oscar_year.insert(0, 'Award Ceremony', 'Oscars')
oscar_year

,Award Ceremony,O_Year,O_Category,O_Nominee,O_Film Title,O_Win
4773,Oscars,1970,ACTOR,Melvyn Douglas,I Never Sang for My Father,False
4774,Oscars,1970,ACTOR,James Earl Jones,The Great White Hope,False
4775,Oscars,1970,ACTOR,Jack Nicholson,Five Easy Pieces,False
4776,Oscars,1970,ACTOR,Ryan O'Neal,Love Story,False
4777,Oscars,1970,ACTOR,George C. Scott,Patton,True
...,...,...,...,...,...,...
10386,Oscars,2019,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
10387,Oscars,2019,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
10388,Oscars,2019,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
10389,Oscars,2019,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
10390,Oscars,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True

In [28]:
oscar_year.to_csv('Output/oscar_cleaned.csv', index=False, header=True)