In [1]:
# Import Dependencies
import pandas as pd

In [2]:
goldeng_csv = 'Output/goldeng_cleaned.csv'
oscars_csv = 'Output/oscar_cleaned.csv'
imbdb_csv = 'Output/imbd_movies_cleaned.csv'

In [3]:
goldeng_df = pd.read_csv(goldeng_csv)
oscars_df = pd.read_csv(oscars_csv)

In [4]:
goldeng_df.columns

Index(['year_film', 'year_award', 'ceremony', 'category', 'nominee', 'film',
       'win'],
      dtype='object')

In [5]:
# goldeng_film = goldeng_df.rename(columns={'GG_Nominee': 'Nominee',
#                                           'GG_Film Title': 'Film'})
# goldeng_film

In [6]:
# goldeng_film = goldeng_film.reset_index(drop=True)
# goldeng_film

In [7]:
oscars_df.columns

Index(['year_film', 'year_ceremony', 'ceremony', 'category', 'name', 'film',
       'winner'],
      dtype='object')

In [17]:
oscars_film = oscars_df.rename(columns={'name': 'nominee',
                                        'winner': 'win'})
oscars_film

,year_film,year_ceremony,ceremony,category,nominee,film,win
0,1970,1971,43,ACTOR,Melvyn Douglas,I Never Sang for My Father,False
1,1970,1971,43,ACTOR,James Earl Jones,The Great White Hope,False
2,1970,1971,43,ACTOR,Jack Nicholson,Five Easy Pieces,False
3,1970,1971,43,ACTOR,Ryan O'Neal,Love Story,False
4,1970,1971,43,ACTOR,George C. Scott,Patton,True
...,...,...,...,...,...,...,...
5482,2019,2020,92,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
5483,2019,2020,92,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
5484,2019,2020,92,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
5485,2019,2020,92,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
5486,2019,2020,92,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True

In [11]:
# oscars_film = oscars_film.reset_index(drop=True)
# oscars_film

In [18]:
film_df = goldeng_df.merge(oscars_film, how='outer', on='film', suffixes=('_golden', '_oscar'))
film_df.head()

,year_film_golden,year_award,ceremony_golden,category_golden,nominee_golden,film,win_golden,year_film_oscar,year_ceremony,ceremony_oscar,category_oscar,nominee_oscar,win_oscar
0,1970.0,1971.0,28.0,Best Performance by an Actress in a Motion Pic...,Ali MacGraw,Love Story,True,1970.0,1971.0,43.0,ACTOR,Ryan O'Neal,False
1,1970.0,1971.0,28.0,Best Performance by an Actress in a Motion Pic...,Ali MacGraw,Love Story,True,1970.0,1971.0,43.0,ACTOR IN A SUPPORTING ROLE,John Marley,False
2,1970.0,1971.0,28.0,Best Performance by an Actress in a Motion Pic...,Ali MacGraw,Love Story,True,1970.0,1971.0,43.0,ACTRESS,Ali MacGraw,False
3,1970.0,1971.0,28.0,Best Performance by an Actress in a Motion Pic...,Ali MacGraw,Love Story,True,1970.0,1971.0,43.0,DIRECTING,Arthur Hiller,False
4,1970.0,1971.0,28.0,Best Performance by an Actress in a Motion Pic...,Ali MacGraw,Love Story,True,1970.0,1971.0,43.0,MUSIC (Original Score),Francis Lai,True

In [19]:
nominee_df = oscars_film.merge(goldeng_df, how='outer', on='nominee', suffixes=('_oscar', '_golden')) 
nominee_df.head()

,year_film_oscar,year_ceremony,ceremony_oscar,category_oscar,nominee,film_oscar,win_oscar,year_film_golden,year_award,ceremony_golden,category_golden,film_golden,win_golden
0,1970.0,1971.0,43.0,ACTOR,Melvyn Douglas,I Never Sang for My Father,False,1970.0,1971.0,28.0,Best Performance by an Actor in a Motion Pictu...,I Never Sang For My Father,False
1,1970.0,1971.0,43.0,ACTOR,Melvyn Douglas,I Never Sang for My Father,False,1979.0,1980.0,37.0,Best Performance by an Actor in a Supporting R...,Being There,True
2,1979.0,1980.0,52.0,ACTOR IN A SUPPORTING ROLE,Melvyn Douglas,Being There,True,1970.0,1971.0,28.0,Best Performance by an Actor in a Motion Pictu...,I Never Sang For My Father,False
3,1979.0,1980.0,52.0,ACTOR IN A SUPPORTING ROLE,Melvyn Douglas,Being There,True,1979.0,1980.0,37.0,Best Performance by an Actor in a Supporting R...,Being There,True
4,1970.0,1971.0,43.0,ACTOR,James Earl Jones,The Great White Hope,False,1970.0,1971.0,28.0,Best Performance by an Actor in a Motion Pictu...,"Great White Hope, The",False

In [39]:
unique_film = film_df['film'].unique()
len(unique_film)

4326

In [40]:
post={
    'film': '',
    'year': '',
    'oscar_nominations': [],
    'golden_nominations': [],
}

In [47]:
i = 0

for film in unique_film:
    df = film_df[film_df['film'] == film]
    post = {
        'film': film,
        'oscar_nominations': [],
        'golden_nominations': [],
    }
    golden_nominations = df['category_golden'].unique()
    for nomination in golden_nominations:
        tf = df[df['category_golden'] == nomination]
        try:
            
            cat_nom = {
                'year_film': tf['year_film_golden'].iloc[0],
                'year_award': tf['year_award'].iloc[0] ,
                'category':  tf['category_golden'].iloc[0],
                'nominee':  tf['nominee_golden'].iloc[0],
                'win': tf['win_golden'].iloc[0]

            }
            post['golden_nominations'].append(cat_nom)
        except:
            pass
        
    oscar_nominations = df['category_oscar'].unique()
    for nomination in oscar_nominations:
        tf = df[df['category_oscar'] == nomination]
        try:
            
            cat_nom = {
                'year_film': tf['year_film_oscar'].iloc[0],
                'year_award': tf['year_ceremony'].iloc[0] ,
                'category':  tf['category_oscar'].iloc[0],
                'nominee':  tf['nominee_oscar'].iloc[0],
                'win': tf['win_oscar'].iloc[0]

            }
            post['oscar_nominations'].append(cat_nom)
        except:
            pass 
        
    i = i + 1
    if i == 4:
        break

In [42]:
post

{'film': 'Promise at Dawn',
 'oscar_nominations': [],
 'golden_nominations': [{'year_film': 1970.0,
   'year_award': 1971.0,
   'category': 'Best Performance by an Actress in a Motion Picture - Drama',
   'nominee': 'Melina Mercouri',
   'win': False},
  {'year_film': 1970.0,
   'year_award': 1971.0,
   'category': 'New Star Of The Year - Actor',
   'nominee': 'Assaf Dayan',
   'win': False}]}

In [43]:
# df = film_df[film_df['film'] == 'Wilson' ]

In [44]:
# no longer need this

# merge_organize = merge_all[['imdb_title_id', 'Film Title', 'original_title', 'year', 
#                             'date_published', 'genre', 'GG_Ceremony', 'GG_category',
#                             'GG_Nominee_Name', 'GG_Win', 'O_Ceremony', 'O_Category',
#                             'O_Nominee_Name', 'O_Win', 'duration', 'country',
#                             'language', 'director', 'writer', 'production_company',
#                             'actors', 'description', 'avg_vote', 'votes',
#                             'budget', 'usa_gross_income', 'worlwide_gross_income', 'metascore',
#                             'reviews_from_users', 'reviews_from_critics']]
# merge_organize

In [45]:
df

,year_film_golden,year_award,ceremony_golden,category_golden,nominee_golden,film,win_golden,year_film_oscar,year_ceremony,ceremony_oscar,category_oscar,nominee_oscar,win_oscar
46,1970.0,1971.0,28.0,Best Performance by an Actress in a Motion Pic...,Melina Mercouri,Promise at Dawn,False,NaN,NaN,NaN,NaN,NaN,NaN
47,1970.0,1971.0,28.0,New Star Of The Year - Actor,Assaf Dayan,Promise at Dawn,False,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
tf

Empty DataFrame
Columns: [year_film_golden, year_award, ceremony_golden, category_golden, nominee_golden, film, win_golden, year_film_oscar, year_ceremony, ceremony_oscar, category_oscar, nominee_oscar, win_oscar]
Index: []