In [1]:
import pandas as pd

In [2]:
#load each csv file from resources directory
oscar_csv = "Resources/the_oscar_award.csv"
oscar_df= pd.read_csv(oscar_csv)
oscar_df.head()

,year_film,year_ceremony,ceremony,category,name,film,winner
0,1927,1928,1,ACTOR,Richard Barthelmess,The Noose,False
1,1927,1928,1,ACTOR,Emil Jannings,The Last Command,True
2,1927,1928,1,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,1928,1,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,1928,1,ACTRESS,Gloria Swanson,Sadie Thompson,False

In [5]:
reduced = oscar_df[['year_film', 'category', 'name', 'film', 'winner']]
reduced

,year_film,category,name,film,winner
0,1927,ACTOR,Richard Barthelmess,The Noose,False
1,1927,ACTOR,Emil Jannings,The Last Command,True
2,1927,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...
10390,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True
10391,2019,JEAN HERSHOLT HUMANITARIAN AWARD,Geena Davis,NaN,True
10392,2019,HONORARY AWARD,David Lynch,NaN,True
10393,2019,HONORARY AWARD,Wes Studi,NaN,True
10394,2019,HONORARY AWARD,Lina Wertmüller,NaN,True

In [6]:
dropped = reduced.dropna(how='any')
dropped

,year_film,category,name,film,winner
0,1927,ACTOR,Richard Barthelmess,The Noose,False
1,1927,ACTOR,Emil Jannings,The Last Command,True
2,1927,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...
10386,2019,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
10387,2019,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
10388,2019,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
10389,2019,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
10390,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True

In [7]:
renamed = dropped.rename(columns={
                            'year_film': 'Year',
                            'category': 'Award Category',
                            'name': 'Nominee Name',
                            'film': 'Film',
                            'winner': 'Win'
})
renamed

,Year,Award Category,Nominee Name,Film,Win
0,1927,ACTOR,Richard Barthelmess,The Noose,False
1,1927,ACTOR,Emil Jannings,The Last Command,True
2,1927,ACTRESS,Louise Dresser,A Ship Comes In,False
3,1927,ACTRESS,Janet Gaynor,7th Heaven,True
4,1927,ACTRESS,Gloria Swanson,Sadie Thompson,False
...,...,...,...,...,...
10386,2019,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
10387,2019,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
10388,2019,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
10389,2019,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
10390,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True

In [8]:
renamed.dtypes

Year               int64
Award Category    object
Nominee Name      object
Film              object
Win                 bool
dtype: object

In [9]:
year = renamed[renamed['Year'] >= 1970]
year

,Year,Award Category,Nominee Name,Film,Win
4773,1970,ACTOR,Melvyn Douglas,I Never Sang for My Father,False
4774,1970,ACTOR,James Earl Jones,The Great White Hope,False
4775,1970,ACTOR,Jack Nicholson,Five Easy Pieces,False
4776,1970,ACTOR,Ryan O'Neal,Love Story,False
4777,1970,ACTOR,George C. Scott,Patton,True
...,...,...,...,...,...
10386,2019,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
10387,2019,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
10388,2019,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
10389,2019,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
10390,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True

In [10]:
year.insert(0, 'Award Ceremony', 'Oscars')
year

,Award Ceremony,Year,Award Category,Nominee Name,Film,Win
4773,Oscars,1970,ACTOR,Melvyn Douglas,I Never Sang for My Father,False
4774,Oscars,1970,ACTOR,James Earl Jones,The Great White Hope,False
4775,Oscars,1970,ACTOR,Jack Nicholson,Five Easy Pieces,False
4776,Oscars,1970,ACTOR,Ryan O'Neal,Love Story,False
4777,Oscars,1970,ACTOR,George C. Scott,Patton,True
...,...,...,...,...,...,...
10386,Oscars,2019,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
10387,Oscars,2019,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
10388,Oscars,2019,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
10389,Oscars,2019,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
10390,Oscars,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True

In [11]:
oscar_final = year
oscar_final

,Award Ceremony,Year,Award Category,Nominee Name,Film,Win
4773,Oscars,1970,ACTOR,Melvyn Douglas,I Never Sang for My Father,False
4774,Oscars,1970,ACTOR,James Earl Jones,The Great White Hope,False
4775,Oscars,1970,ACTOR,Jack Nicholson,Five Easy Pieces,False
4776,Oscars,1970,ACTOR,Ryan O'Neal,Love Story,False
4777,Oscars,1970,ACTOR,George C. Scott,Patton,True
...,...,...,...,...,...,...
10386,Oscars,2019,WRITING (Original Screenplay),Written by Rian Johnson,Knives Out,False
10387,Oscars,2019,WRITING (Original Screenplay),Written by Noah Baumbach,Marriage Story,False
10388,Oscars,2019,WRITING (Original Screenplay),Written by Sam Mendes & Krysty Wilson-Cairns,1917,False
10389,Oscars,2019,WRITING (Original Screenplay),Written by Quentin Tarantino,Once upon a Time...in Hollywood,False
10390,Oscars,2019,WRITING (Original Screenplay),"Screenplay by Bong Joon Ho, Han Jin Won; Story...",Parasite,True